name: Jekyll site CI

on:
  push:

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@359bebbc29cbe6c87da6bc9ea3bc930432750108
        with:
          ruby-version: '3.1'
          bundler-cache: true
      - name: Install dependencies
        run: bundle install
      - name: Build Static site
        run: bundle exec jekyll build -s . -d ./_site        
      - name: Build DOcker image prod
        if: github.ref == 'refs/heads/master'  
        run: docker build -f ./Dockerfile -t main-latest .
      - name: Build DOcker image stage
        if: github.ref != 'refs/heads/master'
        run: docker build -f ./Dockerfile -t staging-latest .
      - name: Build and Publish latest Docker image
        uses: VaultVulp/gp-docker-action@1.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }} # Provide GITHUB_TOKEN to login into the GitHub Packages
          image-name: timmeeyblog # Provide only Docker image name, tag will be automatically set to latest

        #image: docker.pkg.github.com/timmeey/timmeey-about-everything/timmeeyblog:latest
