name: Jekyll site CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: satackey/action-docker-layer-caching@v0.0.11
      # Ignore the failure of a step and avoid terminating the job.
      continue-on-error: true
    - name: Prepare Docker container with dependencies
      run: |
        docker build --target dependencies .
    - name: Build Jekyll site
      run: |
        docker build --target builder .
